services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  celery:
    build: .
    container_name: celery
    command: celery -A taskDj worker -E -l info
    volumes:
      - .:/app
    environment:
      - DB_HOST=host.docker.internal
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_TIMEZONE=${CELERY_TIMEZONE}
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=${CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP}
    depends_on:
      - redis
