services:
  server:
    build:
      context: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 taskDj.asgi:application"
    ports:
      - 8000:8000
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    volumes:
      - ./static:/app/static
      - ./assignment/uploads:/app/assignment/uploads

  serve-static:
    image: nginx:latest
    depends_on:
      - server
    ports:
      - 80:80
    volumes:
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
